const products = [
  {
    id: "SAR-1001",
    name: "Royal Kanchipuram Silk Saree",
    category: "Silk Sarees",
    price: 2499,
    originalPrice: 3299,
    discount: 24,
    color: "Maroon",
    fabric: "Pure Silk",
    occasion: "Wedding",
    pattern: "Traditional Zari",
    blouseIncluded: true,
    description: "A stunning Royal Kanchipuram Silk Saree featuring intricate golden zari work, perfect for weddings and grand occasions. Woven with pure silk for a rich drape and luxurious feel.",
    images: ["https://images.unsplash.com/photo-1610189013444-24e031a0129c?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1583391733958-6512808de432?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: true,
    bestseller: true,
    rating: 4.8,
    reviews: 124
  },
  {
    id: "SAR-1002",
    name: "Elegant Banarasi Saree",
    category: "Banarasi Sarees",
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    color: "Red",
    fabric: "Banarasi Silk",
    occasion: "Wedding",
    pattern: "Floral Brocade",
    blouseIncluded: true,
    description: "Traditional Banarasi weave in a vibrant red, adorned with heavy floral brocade work. Handloom masterpiece perfect for bridal wear.",
    images: ["https://images.unsplash.com/photo-1583391733958-6512808de432?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1610189013444-24e031a0129c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: true,
    bestseller: false,
    rating: 4.9,
    reviews: 89
  },
  {
    id: "SAR-1003",
    name: "Classic Cotton Handloom Saree",
    category: "Cotton Sarees",
    price: 899,
    originalPrice: 1299,
    discount: 30,
    color: "Blue",
    fabric: "Pure Cotton",
    occasion: "Daily Wear",
    pattern: "Solid with Border",
    blouseIncluded: false,
    description: "Breathable pure cotton handloom saree ideal for daily wear or office wear. Features a subtle contrast border for an elegant touch.",
    images: ["https://images.unsplash.com/photo-1583391733958-6512808de432?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: true,
    rating: 4.5,
    reviews: 210
  },
  {
    id: "SAR-1004",
    name: "Soft Organza Floral Saree",
    category: "Organza Sarees",
    price: 1599,
    originalPrice: 2199,
    discount: 27,
    color: "Pink",
    fabric: "Organza",
    occasion: "Party",
    pattern: "Floral Print",
    blouseIncluded: true,
    description: "Lightweight and ethereal organza saree with delicate digital floral prints. Gives a very modern and chic look for evening parties.",
    images: ["https://images.unsplash.com/photo-1610189013444-24e031a0129c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: true,
    bestseller: false,
    rating: 4.6,
    reviews: 45
  },
  {
    id: "SAR-1005",
    name: "Midnight Blue Chiffon Saree",
    category: "Chiffon Sarees",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    color: "Blue",
    fabric: "Chiffon",
    occasion: "Party",
    pattern: "Solid",
    blouseIncluded: true,
    description: "A flowy, elegant midnight blue chiffon saree. Easy to drape and perfect for cocktail parties.",
    images: ["https://images.unsplash.com/photo-1583391733958-6512808de432?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: false,
    rating: 4.3,
    reviews: 34
  },
  {
    id: "SAR-1006",
    name: "Vibrant Yellow Georgette Saree",
    category: "Georgette Sarees",
    price: 1450,
    originalPrice: 1800,
    discount: 19,
    color: "Yellow",
    fabric: "Georgette",
    occasion: "Festival",
    pattern: "Embroidered",
    blouseIncluded: true,
    description: "Bright yellow georgette saree with intricate thread embroidery on the borders. Perfect for Haldi or festive occasions.",
    images: ["https://images.unsplash.com/photo-1610189013444-24e031a0129c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: true,
    rating: 4.7,
    reviews: 156
  },
  {
    id: "SAR-1007",
    name: "Emerald Green Mysore Silk Saree",
    category: "Silk Sarees",
    price: 2800,
    originalPrice: 3500,
    discount: 20,
    color: "Green",
    fabric: "Mysore Silk",
    occasion: "Wedding",
    pattern: "Plain with Zari Border",
    blouseIncluded: true,
    description: "Authentic Mysore Silk in a rich emerald green shade, highlighted by a classic pure zari border.",
    images: ["https://images.unsplash.com/photo-1583391733958-6512808de432?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "Low Stock",
    featured: true,
    bestseller: false,
    rating: 4.9,
    reviews: 67
  },
  {
    id: "SAR-1008",
    name: "Black Party Wear Sequins Saree",
    category: "Party Wear",
    price: 3100,
    originalPrice: 4500,
    discount: 31,
    color: "Black",
    fabric: "Net/Georgette Blend",
    occasion: "Party",
    pattern: "Sequins Work",
    blouseIncluded: true,
    description: "Glamorous black saree completely adorned with sparkling sequins. Be the center of attention at any night event.",
    images: ["https://images.unsplash.com/photo-1610189013444-24e031a0129c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: true,
    rating: 4.8,
    reviews: 92
  },
  {
    id: "SAR-1009",
    name: "Pure Linen Pastel Saree",
    category: "Daily Wear",
    price: 1750,
    originalPrice: 2200,
    discount: 20,
    color: "Pink",
    fabric: "Linen",
    occasion: "Office",
    pattern: "Stripes",
    blouseIncluded: true,
    description: "Sophisticated pastel pink linen saree with subtle metallic stripes. Highly comfortable for long office hours.",
    images: ["https://images.unsplash.com/photo-1583391733958-6512808de432?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: false,
    rating: 4.4,
    reviews: 51
  },
  {
    id: "SAR-1010",
    name: "White Kerala Kasavu Saree",
    category: "Traditional",
    price: 1200,
    originalPrice: 1500,
    discount: 20,
    color: "White",
    fabric: "Cotton Blend",
    occasion: "Festival",
    pattern: "Gold Border",
    blouseIncluded: true,
    description: "Traditional pristine white Kasavu saree with a broad golden zari border. Essential for Onam and Vishu celebrations.",
    images: ["https://images.unsplash.com/photo-1610189013444-24e031a0129c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: true,
    bestseller: true,
    rating: 4.7,
    reviews: 180
  },
  {
    id: "SAR-1011",
    name: "Purple Art Silk Saree",
    category: "Silk Sarees",
    price: 999,
    originalPrice: 1499,
    discount: 33,
    color: "Purple",
    fabric: "Art Silk",
    occasion: "Festival",
    pattern: "Printed",
    blouseIncluded: true,
    description: "Affordable and lustrous purple art silk saree featuring ethnic prints. Great for casual festive gatherings.",
    images: ["https://images.unsplash.com/photo-1583391733958-6512808de432?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: false,
    rating: 4.2,
    reviews: 29
  },
  {
    id: "SAR-1012",
    name: "Orange Bandhani Saree",
    category: "Georgette Sarees",
    price: 1899,
    originalPrice: 2500,
    discount: 24,
    color: "Orange",
    fabric: "Georgette",
    occasion: "Festival",
    pattern: "Bandhani Print",
    blouseIncluded: true,
    description: "Vibrant orange Bandhani printed georgette saree, showcasing traditional Rajasthani tie-dye patterns.",
    images: ["https://images.unsplash.com/photo-1610189013444-24e031a0129c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: true,
    rating: 4.6,
    reviews: 105
  },
  {
    id: "SAR-1013",
    name: "Golden Tissue Silk Saree",
    category: "Silk Sarees",
    price: 4500,
    originalPrice: 6000,
    discount: 25,
    color: "Gold",
    fabric: "Tissue Silk",
    occasion: "Wedding",
    pattern: "Metallic Shimmer",
    blouseIncluded: true,
    description: "Exquisite golden tissue silk saree with a brilliant metallic shimmer. The ultimate bridal or bridesmaid choice.",
    images: ["https://images.unsplash.com/photo-1583391733958-6512808de432?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "Out of Stock",
    featured: true,
    bestseller: false,
    rating: 4.9,
    reviews: 42
  },
  {
    id: "SAR-1014",
    name: "Grey Silver Zari Cotton Silk Saree",
    category: "Blend",
    price: 1350,
    originalPrice: 1900,
    discount: 28,
    color: "Grey",
    fabric: "Cotton Silk",
    occasion: "Office",
    pattern: "Geometric",
    blouseIncluded: true,
    description: "Contemporary grey cotton silk saree with silver zari geometric patterns. Balances traditional weave with modern aesthetics.",
    images: ["https://images.unsplash.com/photo-1610189013444-24e031a0129c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: false,
    rating: 4.5,
    reviews: 63
  },
  {
    id: "SAR-1015",
    name: "Maroon Velvet Border Chiffon Saree",
    category: "Chiffon Sarees",
    price: 2100,
    originalPrice: 2800,
    discount: 25,
    color: "Maroon",
    fabric: "Chiffon",
    occasion: "Party",
    pattern: "Velvet Border",
    blouseIncluded: true,
    description: "Deep maroon chiffon saree elevated with a heavy embroidered velvet border. Very elegant for evening events.",
    images: ["https://images.unsplash.com/photo-1583391733958-6512808de432?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: false,
    rating: 4.7,
    reviews: 74
  },
  {
    id: "SAR-1016",
    name: "Peacock Blue Paithani Saree",
    category: "Silk Sarees",
    price: 5500,
    originalPrice: 7500,
    discount: 26,
    color: "Blue",
    fabric: "Pure Silk",
    occasion: "Wedding",
    pattern: "Peacock Motifs",
    blouseIncluded: true,
    description: "Luxurious pure silk Paithani saree featuring intricate peacock motifs on the pallu and an opulent zari border.",
    images: ["https://images.unsplash.com/photo-1610189013444-24e031a0129c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: true,
    bestseller: false,
    rating: 5.0,
    reviews: 21
  },
  {
    id: "SAR-1017",
    name: "Simple Red Georgette Ruffle Saree",
    category: "Party Wear",
    price: 1600,
    originalPrice: 2200,
    discount: 27,
    color: "Red",
    fabric: "Georgette",
    occasion: "Party",
    pattern: "Ruffled",
    blouseIncluded: true,
    description: "Trendy pre-stitched ruffle saree in vibrant red georgette. Fun, modern, and easy to wear.",
    images: ["https://images.unsplash.com/photo-1583391733958-6512808de432?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: true,
    rating: 4.4,
    reviews: 133
  },
  {
    id: "SAR-1018",
    name: "White & Gold Chanderi Saree",
    category: "Cotton Sarees",
    price: 1950,
    originalPrice: 2600,
    discount: 25,
    color: "White",
    fabric: "Chanderi Cotton",
    occasion: "Festival",
    pattern: "Butti Work",
    blouseIncluded: true,
    description: "Elegant Chanderi cotton saree in off-white with delicate gold zari butti work throughout.",
    images: ["https://images.unsplash.com/photo-1610189013444-24e031a0129c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: false,
    rating: 4.6,
    reviews: 58
  },
  {
    id: "SAR-1019",
    name: "Magenta Gadwal Silk Saree",
    category: "Silk Sarees",
    price: 3200,
    originalPrice: 4000,
    discount: 20,
    color: "Purple",
    fabric: "Gadwal Silk",
    occasion: "Wedding",
    pattern: "Contrast Border",
    blouseIncluded: true,
    description: "Traditional Gadwal silk saree in striking magenta with a contrasting green zari border.",
    images: ["https://images.unsplash.com/photo-1583391733958-6512808de432?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: false,
    rating: 4.8,
    reviews: 44
  },
  {
    id: "SAR-1020",
    name: "Black & White Ikat Cotton Saree",
    category: "Cotton Sarees",
    price: 1100,
    originalPrice: 1600,
    discount: 31,
    color: "Black",
    fabric: "Pure Cotton",
    occasion: "Office",
    pattern: "Ikat Print",
    blouseIncluded: false,
    description: "Classic monochrome pure cotton saree with authentic Ikat prints. Very comfortable and professional.",
    images: ["https://images.unsplash.com/photo-1610189013444-24e031a0129c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "In Stock",
    featured: false,
    bestseller: true,
    rating: 4.5,
    reviews: 198
  }
];

window.products = products;
